-- create schema VoixDuRenard; --
-- Use VoixDuRenard;--
-- MySQL Script generated by MySQL Workbench
-- Fri Nov 20 19:44:17 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`formulaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formulaire` (
  `idform` INT NOT NULL AUTO_INCREMENT,
  `dateform` DATE NULL,
  `nomform` VARCHAR(45) NULL,
  `objetform` VARCHAR(45) NULL,
  `Contenuform` TINYTEXT NULL,
  `emailform` VARCHAR(45) NULL,
  PRIMARY KEY (`idform`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`personne` (
  `idindividu` INT NOT NULL AUTO_INCREMENT,
  `Nomindivu` VARCHAR(45) NULL,
  `prenomindividu` VARCHAR(45) NULL,
  `courielindividu` VARCHAR(45) NULL,
  `formulaire_idform` INT NOT NULL,
  PRIMARY KEY (`idindividu`),
  INDEX `fk_personne_formulaire1_idx` (`formulaire_idform` ASC) VISIBLE,
  CONSTRAINT `fk_personne_formulaire1`
    FOREIGN KEY (`formulaire_idform`)
    REFERENCES `mydb`.`formulaire` (`idform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`abonne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`abonne` (
  `pseudo abonne` VARCHAR(45) NOT NULL,
  `idindividu` INT NOT NULL,
  `nomindidu` VARCHAR(45) NULL,
  `prenomindividu` VARCHAR(45) NULL,
  PRIMARY KEY (`pseudo abonne`, `idindividu`),
  INDEX `fk_idindividu_idx` (`idindividu` ASC) VISIBLE,
  CONSTRAINT `fk_idindividu`
    FOREIGN KEY (`idindividu`)
    REFERENCES `mydb`.`personne` (`idindividu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`podcast`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`podcast` (
  `idpodcast` INT NOT NULL AUTO_INCREMENT,
  `titrepodcast` VARCHAR(45) NULL,
  `presentateur` INT NULL,
  `nblikes` INT NULL,
  `nbdislike` INT NULL,
  `nbEcoute` INT NULL,
  `nbCommen taire` INT NULL,
  `descpodcast` VARCHAR(255) NULL,
  `dureePodcast` VARCHAR(45) NULL,
  `datepodcast` DATE NULL,
  PRIMARY KEY (`idpodcast`),
  INDEX `fk_presentateur_idx` (`presentateur` ASC) VISIBLE,
  CONSTRAINT `fk_presentateur`
    FOREIGN KEY (`presentateur`)
    REFERENCES `mydb`.`personne` (`idindividu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Commentaire` (
  `idCommentaire` INT NOT NULL AUTO_INCREMENT,
  `refpodcast` INT NULL,
  `contenuCom` MEDIUMTEXT NULL,
  `PseudoCom` VARCHAR(45) NULL,
  `datecomm` DATE NULL,
  PRIMARY KEY (`idCommentaire`),
  INDEX `fk_refpodcast_idx` (`refpodcast` ASC) VISIBLE,
  INDEX `fk_pseudoabo_idx` (`PseudoCom` ASC) VISIBLE,
  CONSTRAINT `fk_refpodcast`
    FOREIGN KEY (`refpodcast`)
    REFERENCES `mydb`.`podcast` (`idpodcast`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pseudoabo`
    FOREIGN KEY (`PseudoCom`)
    REFERENCES `mydb`.`abonne` (`pseudo abonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
